# Films Reviews

### Goal: 
You are a Machine Learning Engineer in XYZ. Reviews of a set of films are given to you and your goal is to build a classification model and predict reviews as negative or positive which helps customers in one of deciding factors to watch a film.

### Data Description: 
The given data is about reviews of different films from multiple genres and different languages.

### Attribute Information:
- id: Unique identifier for each row.
- category: The reviews have been categorized into two categories representing positive review and negative review. 0 represents positive review and 1 represents a negative review.
- text: review is basically text data and that has been Tokenized for all reviews in training and testing sets.

### Objective Of The Problem: 
The objective of the problem is to predict the categories of the “text” attribute in the “Test file” and write the same into a CSV (Comma Separated Values) along with the “id” attribute. Please note that one to one mapping exists between all the attributes and the same must be preserved. Upload the predicted solution file using the upload file field below and click on submit to get a score. View the sample submission file to get an understanding of how the solution file must be written. Please note that the headers of the solution file being uploaded should be the same as the headers of the sample submission file.

### Evaluation Criteria: 
The evaluation metric for this problem statement is precision-based accuracy. All scores would be normalized to 100. If predictions are to be made for “y” tuples and “x” tuples are predicted with correctness, then the score assigned would be (x/y * 100)

In [287]:
import pandas as pd
import numpy as np
import nltk
import matplotlib.pyplot as plt

In [288]:
train = pd.read_csv(r"D:\denis\training_nlp skillnza.csv")

test = pd.read_csv(r"D:\denis\test_nlp skillnza.csv")

In [289]:
print(train.category.value_counts())
print("----------------------")
print(train.shape)

0    3348
1     116
Name: category, dtype: int64
----------------------
(3464, 3)

In [290]:
train.head()

    id  category                                               text
0  959         0    5573 1189 4017 1207 4768 8542 17 1189 5085 5773
1  994         0       6315 7507 6700 4742 1944 2692 3647 4413 6700
2  995         0                      5015 8067 5335 1615 7957 5773
3  996         0  2925 7199 1994 4647 7455 5773 4518 2734 2807 8...
4  997         0                  7136 1207 6781 237 4971 3669 6193

In [291]:
test.head()

     id                                               text
0  3729  2705 4888 5050 5815 2472 5157 652 2117 2110 32...
1  3732  389 4978 315 5178 513 5249 5853 3267 315 3891 ...
2  3761  4478 4231 4858 2638 4231 867 371 686 4888 4179...
3     5  3015 1911 112 3905 825 337 315 1693 4677 825 5...
4     7  5136 3918 5153 2023 3091 4159 315 3711 1409 27...

In [292]:
from sklearn.feature_extraction.text import CountVectorizer

bow_transformer = CountVectorizer().fit(train['text'])

print(len(bow_transformer.vocabulary_))

8484

In [293]:
#train Data
train_bow = bow_transformer.transform(train.text) 
#creating TDM
train_bow.shape

(3464, 8484)

In [294]:
bow_transformer.vocabulary_

{'5573': 4986,
 '1189': 208,
 '4017': 3288,
 '1207': 229,
 '4768': 4112,
 '8542': 8230,
 '17': 765,
 '5085': 4456,
 '5773': 5203,
 '6315': 5798,
 '7507': 7103,
 '6700': 6219,
 '4742': 4084,
 '1944': 1034,
 '2692': 1845,
 '3647': 2886,
 '4413': 3722,
 '5015': 4383,
 '8067': 7713,
 '5335': 4726,
 '1615': 674,
 '7957': 7593,
 '2925': 2101,
 '7199': 6763,
 '1994': 1089,
 '4647': 3980,
 '7455': 7046,
 '4518': 3838,
 '2734': 1891,
 '2807': 1972,
 '853': 8216,
 '2283': 1402,
 '753': 7128,
 '5107': 4481,
 '5922': 5368,
 '4355': 3658,
 '6054': 5514,
 '4608': 3938,
 '2199': 1311,
 '142': 460,
 '4211': 3502,
 '8103': 7754,
 '7747': 7365,
 '7136': 6695,
 '6781': 6307,
 '237': 1497,
 '4971': 4334,
 '3669': 2910,
 '6193': 5664,
 '6730': 6252,
 '3349': 2563,
 '2325': 1448,
 '7714': 7330,
 '5172': 4549,
 '6254': 5730,
 '4097': 3376,
 '6500': 6002,
 '6927': 6466,
 '5045': 4414,
 '3533': 2766,
 '3255': 2459,
 '3225': 2427,
 '6110': 5576,
 '6912': 6450,
 '7732': 7349,
 '3283': 2490,
 '2698': 1851,
 '220': 1313,
 '8431': 8111,
 '2641': 1789,
 '4122': 3405,
 '4675': 4010,
 '5175': 4552,
 '8465': 8146,
 '5395': 4791,
 '5703': 5128,
 '4297': 3595,
 '6794': 6321,
 '714': 6699,
 '4164': 3450,
 '5672': 5095,
 '8124': 7776,
 '7674': 7285,
 '4947': 4308,
 '7671': 7282,
 '4335': 3636,
 '1587': 643,
 '6589': 6096,
 '6517': 6020,
 '326': 2464,
 '8380': 8057,
 '7343': 6924,
 '6084': 5547,
 '779': 7412,
 '3485': 2712,
 '5141': 4516,
 '3078': 2267,
 '1976': 1069,
 '4108': 3389,
 '5439': 4840,
 '4973': 4336,
 '224': 1355,
 '4442': 3754,
 '7792': 7415,
 '5893': 5335,
 '6546': 6051,
 '6949': 6490,
 '1309': 339,
 '528': 4665,
 '784': 7468,
 '7879': 7510,
 '3385': 2603,
 '230': 1421,
 '7350': 6932,
 '2963': 2142,
 '7473': 7066,
 '4456': 3769,
 '941': 8421,
 '826': 7925,
 '739': 6974,
 '3899': 3160,
 '7107': 6663,
 '6919': 6457,
 '4676': 4011,
 '7526': 7124,
 '2875': 2046,
 '7182': 6745,
 '4580': 3907,
 '2266': 1383,
 '3342': 2556,
 '7113': 6670,
 '6739': 6261,
 '8095': 7744,
 '5597': 5012,
 '5441': 4843,
 '5483': 4886,
 '657': 6076,
 '3531': 2764,
 '281': 1974,
 '6521': 6025,
 '7152': 6713,
 '1520': 570,
 '546': 4861,
 '1256': 282,
 '6300': 5782,
 '1484': 530,
 '746': 7051,
 '4801': 4149,
 '1278': 305,
 '5328': 4718,
 '2164': 1275,
 '5598': 5013,
 '3601': 2839,
 '2134': 1242,
 '1041': 46,
 '5094': 4466,
 '1499': 546,
 '2977': 2157,
 '8066': 7712,
 '2031': 1129,
 '2423': 1554,
 '1273': 300,
 '2230': 1345,
 '5795': 5227,
 '6514': 6017,
 '8406': 8083,
 '8105': 7756,
 '1325': 356,
 '163': 690,
 '8631': 8327,
 '1253': 279,
 '8125': 7777,
 '6465': 5963,
 '907': 8383,
 '3439': 2661,
 '6478': 5977,
 '6225': 5700,
 '4503': 3822,
 '2573': 1714,
 '6234': 5710,
 '676': 6283,
 '349': 2717,
 '25': 1635,
 '3730': 2977,
 '5894': 5336,
 '572': 5146,
 '6744': 6267,
 '203': 1127,
 '6461': 5959,
 '4121': 3404,
 '7027': 6574,
 '7924': 7557,
 '1939': 1028,
 '5234': 4616,
 '6843': 6375,
 '1251': 277,
 '5343': 4735,
 '942': 8422,
 '4938': 4298,
 '2295': 1415,
 '1088': 97,
 '2779': 1940,
 '4194': 3482,
 '2176': 1287,
 '1444': 486,
 '5300': 4689,
 '2347': 1472,
 '6658': 6171,
 '1834': 913,
 '5869': 5308,
 '2121': 1228,
 '8182': 7840,
 '1647': 708,
 '1556': 609,
 '5285': 4671,
 '3286': 2493,
 '7860': 7491,
 '4586': 3913,
 '7937': 7571,
 '791': 7542,
 '1543': 595,
 '5143': 4518,
 '6655': 6168,
 '5828': 5264,
 '1240': 265,
 '1008': 10,
 '3547': 2781,
 '8256': 7921,
 '7986': 7625,
 '6270': 5748,
 '2240': 1356,
 '7519': 7116,
 '1846': 926,
 '5658': 5080,
 '5071': 4443,
 '5116': 4490,
 '2269': 1386,
 '48': 4146,
 '4976': 4339,
 '4144': 3429,
 '2440': 1572,
 '2612': 1758,
 '2513': 1649,
 '5118': 4492,
 '5915': 5360,
 '438': 3685,
 '254': 1678,
 '6086': 5548,
 '2609': 1754,
 '3604': 2842,
 '8584': 8275,
 '3302': 2512,
 '5273': 4658,
 '3527': 2759,
 '44': 3706,
 '2154': 1264,
 '5551': 4962,
 '3468': 2693,
 '3287': 2494,
 '1095': 105,
 '5092': 4464,
 '8486': 8168,
 '6625': 6137,
 '1784': 858,
 '3743': 2991,
 '7812': 7438,
 '1089': 98,
 '5270': 4655,
 '4184': 3471,
 '7444': 7034,
 '105': 55,
 '6527': 6031,
 '7408': 6994,
 '1813': 891,
 '4139': 3423,
 '2808': 1973,
 '7807': 7432,
 '3934': 3198,
 '5050': 4420,
 '1275': 302,
 '1703': 770,
 '3332': 2545,
 '4179': 3466,
 '6556': 6062,
 '7538': 7137,
 '3818': 3073,
 '7685': 7297,
 '3968': 3234,
 '6031': 5489,
 '3474': 2700,
 '4537': 3859,
 '2275': 1393,
 '3898': 3159,
 '7771': 7392,
 '4252': 3546,
 '6220': 5695,
 '5868': 5307,
 '5466': 4867,
 '6560': 6066,
 '1917': 1004,
 '154': 591,
 '1990': 1085,
 '5244': 4627,
 '263': 1777,
 '6591': 6099,
 '2940': 2118,
 '4357': 3660,
 '4727': 4067,
 '4948': 4309,
 '5063': 4434,
 '6349': 5835,
 '4678': 4013,
 '1872': 955,
 '4533': 3855,
 '3964': 3230,
 '2180': 1291,
 '4841': 4193,
 '6963': 6506,
 '3596': 2832,
 '4927': 4287,
 '6419': 5912,
 '7761': 7381,
 '5620': 5039,
 '3242': 2446,
 '2002': 1098,
 '3866': 3124,
 '6169': 5639,
 '7718': 7334,
 '1659': 721,
 '4318': 3619,
 '4138': 3422,
 '8207': 7868,
 '1908': 994,
 '1519': 568,
 '6712': 6232,
 '2086': 1188,
 '1698': 763,
 '1364': 398,
 '3581': 2816,
 '8600': 8293,
 '307': 2259,
 '8604': 8297,
 '5779': 5209,
 '4196': 3484,
 '562': 5038,
 '5373': 4767,
 '1179': 198,
 '569': 5113,
 '6013': 5469,
 '8155': 7810,
 '1493': 540,
 '7241': 6811,
 '5537': 4946,
 '5713': 5139,
 '5462': 4864,
 '2634': 1782,
 '2451': 1584,
 '6619': 6130,
 '3454': 2678,
 '7005': 6550,
 '3270': 2476,
 '7018': 6564,
 '1457': 500,
 '5819': 5254,
 '7312': 6890,
 '5215': 4595,
 '526': 4644,
 '8057': 7702,
 '7627': 7233,
 '5457': 4859,
 '1755': 826,
 '3668': 2909,
 '4912': 4271,
 '1651': 713,
 '5239': 4621,
 '1489': 535,
 '4178': 3465,
 '1313': 343,
 '3718': 2963,
 '727': 6842,
 '3590': 2826,
 '3500': 2730,
 '7721': 7338,
 '1948': 1038,
 '3821': 3077,
 '1925': 1013,
 '3477': 2703,
 '1086': 95,
 '5534': 4943,
 '1789': 863,
 '6248': 5723,
 '3865': 3123,
 '1385': 421,
 '3656': 2896,
 '2700': 1855,
 '7669': 7279,
 '6496': 5996,
 '1802': 879,
 '5907': 5351,
 '3924': 3187,
 '1824': 903,
 '4929': 4289,
 '2069': 1170,
 '755': 7150,
 '2457': 1590,
 '5694': 5117,
 '7605': 7210,
 '3208': 2409,
 '6265': 5742,
 '1407': 446,
 '378': 3031,
 '787': 7500,
 '3000': 2183,
 '4069': 3345,
 '3442': 2665,
 '3799': 3051,
 '6782': 6308,
 '1486': 532,
 '5697': 5120,
 '5096': 4468,
 '4032': 3305,
 '5579': 4992,
 '3123': 2316,
 '8573': 8263,
 '5243': 4626,
 '5837': 5274,
 '4883': 4238,
 '4995': 4360,
 '1295': 324,
 '6416': 5909,
 '8257': 7922,
 '3577': 2812,
 '183': 909,
 '5821': 5257,
 '1774': 847,
 '7762': 7382,
 '7400': 6986,
 '3320': 2532,
 '4571': 3897,
 '3103': 2294,
 '8166': 7822,
 '118': 199,
 '2348': 1473,
 '2317': 1439,
 '8504': 8189,
 '5323': 4713,
 '8528': 8214,
 '3275': 2481,
 '7566': 7167,
 '7902': 7534,
 '3651': 2891,
 '4819': 4168,
 '5514': 4921,
 '228': 1398,
 '1780': 854,
 '5219': 4599,
 '4160': 3446,
 '2728': 1884,
 '2147': 1256,
 '1226': 250,
 '4904': 4262,
 '6311': 5794,
 '1289': 317,
 '7127': 6685,
 '6863': 6397,
 '1796': 871,
 '3321': 2533,
 '6999': 6542,
 '3825': 3081,
 '3626': 2864,
 '1462': 506,
 '7642': 7250,
 '4041': 3315,
 '3361': 2577,
 '1094': 104,
 '626': 5736,
 '2722': 1878,
 '4695': 4032,
 '8084': 7732,
 '2645': 1793,
 '590': 5343,
 '2242': 1358,
 '4408': 3716,
 '3056': 2244,
 '4557': 3881,
 '6071': 5533,
 '2297': 1417,
 '7171': 6733,
 '6953': 6495,
 '1942': 1032,
 '6341': 5827,
 '1886': 970,
 '5152': 4528,
 '7283': 6857,
 '7565': 7166,
 '3692': 2934,
 '5409': 4807,
 '6170': 5641,
 '6640': 6153,
 '2679': 1830,
 '2869': 2039,
 '5479': 4881,
 '2776': 1937,
 '285': 2018,
 '6424': 5918,
 '7920': 7554,
 '198': 1073,
 '4589': 3916,
 '6898': 6433,
 '7435': 7024,
 '4567': 3892,
 '8138': 7791,
 '2835': 2002,
 '8278': 7945,
 '77': 7313,
 '3894': 3155,
 '7767': 7387,
 '6026': 5483,
 '7982': 7621,
 '1224': 248,
 '4559': 3883,
 '431': 3610,
 '12': 220,
 '4799': 4145,
 '6024': 5481,
 '834': 8014,
 '4037': 3310,
 '1759': 830,
 '244': 1571,
 '5348': 4740,
 '4878': 4232,
 '3092': 2283,
 '6343': 5829,
 '3746': 2994,
 '4986': 4350,
 '5121': 4495,
 '3279': 2485,
 '468': 4015,
 '1656': 718,
 '8370': 8047,
 '7805': 7430,
 '1228': 252,
 '8325': 7998,
 '8298': 7967,
 '93': 8408,
 '7836': 7464,
 '8040': 7685,
 '4508': 3827,
 '1330': 362,
 '5194': 4573,
 '6688': 6204,
 '4756': 4099,
 '3455': 2679,
 '7766': 7386,
 '661': 6120,
 '7542': 7142,
 '3119': 2311,
 '2655': 1804,
 '1631': 692,
 '5772': 5202,
 '3678': 2919,
 '7694': 7307,
 '7558': 7158,
 '2625': 1772,
 '1459': 502,
 '6938': 6478,
 '160': 658,
 '2620': 1767,
 '6918': 6456,
 '138': 415,
 '5823': 5259,
 '716': 6721,
 '7793': 7416,
 '1255': 281,
 '150': 548,
 '2845': 2013,
 '1080': 89,
 '1628': 688,
 '4369': 3673,
 '2701': 1856,
 '6537': 6042,
 '8364': 8040,
 '2726': 1882,
 '7279': 6852,
 '4096': 3375,
 '4493': 3810,
 '7806': 7431,
 '5746': 5175,
 '761': 7215,
 '2670': 1821,
 '445': 3762,
 '6985': 6529,
 '1833': 912,
 '8321': 7994,
 '5166': 4543,
 '4159': 3445,
 '4277': 3573,
 '8551': 8240,
 '1192': 212,
 '1262': 289,
 '1280': 308,
 '3160': 2357,
 '7419': 7006,
 '6387': 5877,
 '7798': 7421,
 '5193': 4572,
 '7096': 6650,
 '8411': 8089,
 '7304': 6881,
 '3594': 2830,
 '4876': 4230,
 '1800': 877,
 '144': 482,
 '6988': 6531,
 '3285': 2492,
 '4944': 4305,
 '6448': 5944,
 '1617': 676,
 '5881': 5322,
 '1713': 781,
 '5536': 4945,
 '480': 4147,
 '6145': 5614,
 '7973': 7611,
 '7556': 7156,
 '331': 2520,
 '1024': 28,
 '6551': 6057,
 '3284': 2491,
 '3422': 2643,
 '474': 4081,
 '4895': 4251,
 '46': 3928,
 '3549': 2783,
 '4701': 4040,
 '1337': 369,
 '7331': 6911,
 '6216': 5690,
 '245': 1582,
 '3507': 2737,
 '5728': 5155,
 '6403': 5896,
 '300': 2182,
 '5427': 4827,
 '5655': 5077,
 '2067': 1168,
 '34': 2618,
 '7284': 6858,
 '6761': 6285,
 '7874': 7505,
 '1782': 856,
 '7295': 6870,
 '990': 8474,
 '210': 1204,
 '8203': 7864,
 '8602': 8295,
 '2945': 2123,
 '6818': 6347,
 '1929': 1017,
 '6277': 5755,
 '5430': 4831,
 '6214': 5688,
 '7341': 6922,
 '1540': 592,
 '2968': 2147,
 '341': 2630,
 '2540': 1679,
 '3125': 2318,
 '6384': 5874,
 '270': 1854,
 '188': 963,
 '1419': 459,
 '6472': 5971,
 '5432': 4833,
 '550': 4905,
 '1827': 906,
 '2933': 2110,
 '5100': 4474,
 '1248': 273,
 '7167': 6729,
 '4702': 4041,
 '5174': 4551,
 '2417': 1547,
 '4715': 4055,
 '6767': 6291,
 '1124': 138,
 '5245': 4628,
 '30': 2181,
 '3073': 2262,
 '4951': 4312,
 '7614': 7219,
 '5150': 4526,
 '6945': 6486,
 '5164': 4541,
 '2800': 1965,
 '6758': 6281,
 '5750': 5180,
 '2064': 1165,
 '4809': 4157,
 '1947': 1037,
 '7442': 7032,
 '1652': 714,
 '3080': 2270,
 '7466': 7058,
 '8491': 8174,
 '205': 1149,
 '2636': 1784,
 '8064': 7710,
 '6964': 6507,
 '3503': 2733,
 '3739': 2986,
 '3372': 2589,
 '2923': 2099,
 '8038': 7682,
 '6686': 6202,
 '5006': 4373,
 '3117': 2309,
 '3950': 3215,
 '5083': 4454,
 '895': 8371,
 '6292': 5772,
 '1425': 466,
 '3501': 2731,
 '4796': 4142,
 '3920': 3183,
 '8518': 8204,
 '8634': 8330,
 '8538': 8225,
 '8028': 7672,
 '2715': 1870,
 '8075': 7722,
 '343': 2651,
 '2928': 2104,
 '8252': 7917,
 '2186': 1297,
 '519': 4568,
 '2624': 1771,
 '2900': 2075,
 '4731': 4072,
 '3882': 3142,
 '5484': 4887,
 '1978': 1071,
 '5575': 4988,
 '8488': 8170,
 '1395': 432,
 '5223': 4604,
 '4477': 3792,
 '3554': 2789,
 '3196': 2395,
 '6481': 5980,
 '7882': 7512,
 '472': 4059,
 '5826': 5262,
 '711': 6666,
 '3671': 2913,
 '1416': 456,
 '2091': 1194,
 '5199': 4578,
 '1463': 507,
 '6161': 5631,
 '2578': 1719,
 '3584': 2819,
 '8612': 8306,
 '1145': 161,
 '8302': 7973,
 '992': 8476,
 '1000': 2,
 '5961': 5411,
 '7333': 6913,
 '4858': 4210,
 '6134': 5602,
 '2140': 1249,
 '6174': 5645,
 '8018': 7661,
 '8511': 8197,
 '8435': 8115,
 '265': 1798,
 '1904': 990,
 '7354': 6936,
 '1984': 1078,
 '1156': 173,
 '3592': 2828,
 '6226': 5701,
 '843': 8109,
 '6451': 5948,
 '3771': 3022,
 '2402': 1531,
 '2975': 2155,
 '651': 6012,
 '7624': 7230,
 '8458': 8139,
 '33': 2508,
 '6439': 5934,
 '5813': 5248,
 '7231': 6800,
 '5255': 4639,
 '7744': 7362,
 '6976': 6519,
 '506': 4430,
 '540': 4797,
 '5841': 5279,
 '1563': 617,
 '1481': 527,
 '3315': 2526,
 '3680': 2921,
 '2082': 1184,
 '3505': 2735,
 '5972': 5423,
 '8448': 8128,
 '2392': 1521,
 '5414': 4813,
 '2507': 1643,
 '2501': 1638,
 '1125': 139,
 '1679': 742,
 '4931': 4292,
 '2263': 1380,
 '7751': 7370,
 '421': 3500,
 '2006': 1102,
 '3379': 2596,
 '3538': 2771,
 '91': 8386,
 '5679': 5102,
 '3300': 2510,
 '3373': 2590,
 '4368': 3672,
 '7141': 6701,
 '7499': 7094,
 '8543': 8231,
 '7248': 6818,
 '8193': 7852,
 '4130': 3414,
 '5636': 5056,
 '7891': 7521,
 '1247': 272,
 '8350': 8026,
 '4177': 3464,
 '76': 7203,
 '1588': 644,
 '7181': 6744,
 '3269': 2474,
 '8171': 7828,
 '6532': 6037,
 '8566': 8255,
 '8266': 7932,
 '529': 4676,
 '3139': 2333,
 '1194': 214,
 '7615': 7220,
 '3766': 3016,
 '5848': 5285,
 '7549': 7149,
 '7531': 7130,
 '5878': 5318,
 '4749': 4091,
 '6809': 6337,
 '4521': 3842,
 '7240': 6810,
 '2129': 1236,
 '7126': 6684,
 '8081': 7729,
 '414': 3424,
 '3352': 2567,
 '7622': 7228,
 '8131': 7784,
 '102': 23,
 '8623': 8318,
 '8326': 7999,
 '2333': 1457,
 '4263': 3558,
 '2758': 1917,
 '1740': 811,
 '1062': 69,
 '1090': 100,
 '1953': 1044,
 '2113': 1219,
 '7012': 6558,
 '2861': 2031,
 '7743': 7361,
 '1853': 934,
 '6967': 6510,
 '911': 8388,
 '6699': 6216,
 '3253': 2458,
 '6980': 6524,
 '2994': 2175,
 '7838': 7466,
 '6036': 5494,
 '609': 5552,
 '7356': 6938,
 '2628': 1775,
 '735': 6931,
 '8322': 7995,
 '7028': 6575,
 '3543': 2777,
 '2744': 1902,
 '3777': 3028,
 '2342': 1467,
 '2749': 1907,
 '7903': 7535,
 '5064': 4435,
 '5181': 4559,
 '6428': 5922,
 '4600': 3930,
 '7862': 7493,
 '6452': 5949,
 '1082': 91,
 '5459': 4860,
 '2616': 1762,
 '425': 3543,
 '5326': 4716,
 '6373': 5862,
 '3384': 2602,
 '7943': 7578,
 '4461': 3775,
 '6257': 5733,
 '5921': 5367,
 '2582': 1724,
 '1530': 581,
 '1436': 478,
 '4294': 3592,
 '579': 5221,
 '2487': 1621,
 '7555': 7155,
 '4457': 3770,
 '2508': 1644,
 '7945': 7580,
 '3542': 2776,
 '3751': 3000,
 '534': 4731,
 '310': 2291,
 '622': 5694,
 '7379': 6962,
 '2768': 1928,
 '653': 6034,
 '88': 8357,
 '5558': 4969,
 '3659': 2899,
 '7731': 7348,
 '4759': 4102,
 '5999': 5452,
 '3098': 2288,
 '1047': 52,
 '3291': 2499,
 '6834': 6365,
 '1720': 789,
 '5480': 4883,
 '6826': 6356,
 '5287': 4673,
 '1132': 147,
 '1498': 545,
 '2470': 1604,
 '8554': 8243,
 '7686': 7298,
 '7814': 7440,
 '4331': 3632,
 '4250': 3544,
 '1293': 322,
 '1473': 518,
 '126': 286,
 '5291': 4678,
 '6053': 5513,
 '3812': 3067,
 '4349': 3651,
 '8130': 7783,
 '1938': 1027,
 '7950': 7586,
 '4229': 3521,
 '8437': 8117,
 '4022': 3294,
 '3895': 3156,
 '295': 2128,
 '286': 2029,
 '124': 264,
 '2163': 1274,
 '8283': 7951,
 '1567': 621,
 '5820': 5256,
 '4426': 3736,
 '5334': 4725,
 '6747': 6270,
 '7734': 7351,
 '3126': 2319,
 '7410': 6997,
 '2822': 1988,
 '7470': 7063,
 '2194': 1306,
 '7823': 7450,
 '2967': 2146,
 '5169': 4546,
 '2329': 1452,
 '7880': 7511,
 '1765': 837,
 '3759': 3008,
 '4462': 3776,
 '7907': 7539,
 '1822': 901,
 '1304': 334,
 '6227': 5702,
 ...}

In [295]:
#spliting into train and test
from sklearn.model_selection import train_test_split

In [298]:
train_x, test_x, train_y, test_y = train_test_split(train_bow,train.category,
                                                   test_size = .25 ,random_state = 40,)

In [299]:
print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)

(2598, 8484)
(866, 8484)
(2598,)
(866,)

#  Model building on Naive bayes

In [300]:
# Building Model using naive bayes
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB(alpha=0.0035, fit_prior=True, class_prior=None,)

In [301]:
model = nb.fit(train_x,train_y)

In [302]:
from sklearn.metrics import confusion_matrix

pred_value = nb.predict(test_x)

In [303]:
cm = confusion_matrix(pred_value , test_y)
cm

array([[835,   2],
       [ 12,  17]], dtype=int64)

In [304]:
cm.diagonal().sum()* 100 /cm.sum()

98.38337182448036

In [305]:
from sklearn.metrics import classification_report

In [306]:
classification_report(test_y , pred_value)

'              precision    recall  f1-score   support\n\n           0       1.00      0.99      0.99       847\n           1       0.59      0.89      0.71        19\n\n    accuracy                           0.98       866\n   macro avg       0.79      0.94      0.85       866\nweighted avg       0.99      0.98      0.99       866\n'

## Model  build on Decision Tree

In [307]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
dt=DecisionTreeClassifier(criterion='entropy',
    splitter='best',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=2,
    min_weight_fraction_leaf=0.0001,                      
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    min_impurity_split=None,
    class_weight=None,
    presort='deprecated',
    ccp_alpha=0.00,
)

In [308]:
model1= dt.fit(train_x,train_y)
pred_dt = dt.predict(test_x)

tab_dt = confusion_matrix(pred_dt,test_y)
tab_dt

array([[843,   6],
       [  4,  13]], dtype=int64)

In [309]:
Accuracy = tab_dt.diagonal().sum() / tab_dt.sum()*100
Accuracy

98.84526558891456

In [310]:
test1 = bow_transformer.transform(test.text) 
#creating TDM
test1

<1360x8484 sparse matrix of type '<class 'numpy.int64'>'
	with 27169 stored elements in Compressed Sparse Row format>

In [311]:
test1.shape

(1360, 8484)

In [313]:
pred_value = dt.predict(test1)
pred_value

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [314]:
final_submission10 = pd.DataFrame({"id":test["id"],
                               "category":pred_value})

In [315]:
final_submission10.to_csv("D:\skillinza\problem1/final_submission10.csv",index=False)